name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Build Sphinx HTML
        run: |
          poetry run sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
          cname: ''
